### PR TITLE
Initiate a new build to see if tests fail as they did for downstream testing

### PR DESCRIPTION
**Pull request by yarikoptic**

### CODE REVIEW

**Comment by notestaff** [comment]
@yarikoptic  So it passes here, very odd.  Can you merge this PR, even though it just bumps the build number?   Maybe something changed about conda-forge or conda-smithy, such that the datalad package built earlier fails but the new one succeeds?
(also maybe rerender and then merge?)

**Comment by yarikoptic** [comment]
I am afraid it is just a flaky test.  Or is it consistently (multiple times tried) failing for you? (so may be some minute difference in setup triggers that flaky test)

**Comment by notestaff** [comment]
@yarikoptic It did fail twice.  Differences could be due to changes in conda-smithy, so I'd try re-rendering datalad with latest version and merging this build-bump PR.   Once that's uploaded to anaconda.org , I can try re-running the git-annex PR (after also re-rendering with the same conda-smithy) and see if the difference still exists.

**Comment by yarikoptic** [comment]
ok, lets do that although I am afraid it is just a flaky test reflecting bug in the code. @kyleam has an [idea](https://github.com/datalad/datalad/issues/4921#issuecomment-692756147) on what might be going on.
meanwhile: I have failed to replicate locally using conda built datalad/git-annex (even ran a bogus jitsi meeing in the background to cause IO -- it usually slows everything down considerably)

@conda-forge-admin, please rerender

**Comment by yarikoptic** [comment]
rerendering shows no possible related change... but ok -- we could merge this one if all tests pass etc

**Pull request merged**
