### PR TITLE
update to 0.11.6

### PR DESCRIPTION
**Pull request by notestaff**
Checklist
* [X] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by notestaff** [comment]
@yarikoptic datalad test suite has some failures (with git-annex-7.20190708)

**Comment by yarikoptic** [comment]
uff... ok, I will look into them! Thanks!

**Comment by yarikoptic** [comment]
grr, the
```python
@skip_if(external_versions['cmd:annex'] < '7.20190708+git36', "Needs freshier git-annex")
```
is not in effect:
```shell
$> python -c 'from distutils.version import LooseVersion as LV; print(LV("7.20190708-gbc74eb1") < "7.20190708+git36")' 
False
```
so that test will not be skipped...  and I don't even see that checksum in git-annex history to see if that is (it must be) before the 
```
$> git show 7.20190708+git36-g32d526164    
commit 32d526164298579ae551753c260da4267385c745
Author: eigood <eigood@web>
Date:   Tue Jul 16 23:45:18 2019 +0000

    Added a comment: Add support for bup daemon?
```
:
```shell
(git-annex)hopa:~/proj/git-annex[master]git-annex
$> git describe 7.20190708-gbc74eb1
fatal: Not a valid object name 7.20190708-gbc74eb1

$> git describe bc74eb1
fatal: Not a valid object name bc74eb1
```

situation should resolve "automagically" whenever new git-annex gets into the conda-forge, or we could adjust skip condition here to demand 7.20190717 (based on the date of the commit, even though there is no release like that).  What would you like (me) to do @notestaff? ;-)

**Comment by notestaff** [comment]
I'd adjust the skip condition to reflect the correct version dependency, so that datalad test runs correctly in various environments, not just on conda-forge.  But if you don't want to make a new datalad release on pypi, we can just wait for the new git-annex and add it as a minimum test requirement in the recipe.

**Comment by yarikoptic** [comment]
It is just a niche usecase and test is just a regression test for annex itself, so probably not worth requirement adjustment. I will indeed tune up skip condition (to get included in the next datalad release) and will push a patch here

**Comment by yarikoptic** [comment]
Woohoo all green! I guess let's proceed

**Pull request merged**
