### PR TITLE
update to 0.11.5; add some dependencies based on setup.py; re-render

### PR DESCRIPTION
**Pull request by notestaff**
Checklist
* [X] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by notestaff** [comment]
@yarikoptic tried to update to 0.11.5 but getting test failures

**Comment by yarikoptic** [comment]
Thank you very much. I will look into it tomorrow morning!

**Comment by yarikoptic** [comment]
FWIW
- pushed d196a7d4aa431d8bb1f98eda0e30d8735925dd0d adding post-release test skipping patch
- filed https://github.com/datalad/datalad/issues/3491 and https://github.com/datalad/datalad/issues/3490 since do not have immediate clue and could not reproduce locally yet.  I guess I would later read on again on how to establish the same docker build env locally, unless there is a one liner waiting for me ;-)

**Comment by yarikoptic** [comment]
oh, @kyleam updated on the 3491 - patch is https://github.com/datalad/datalad/pull/3492/files (being tested by travis ATM)

**Comment by yarikoptic** [comment]
let's aim for 0.11.6 in #16

**Pull request closed without merging**
